"""builds a repo's own test image, so registering a repo is enough to run cards on it.

Detects the stack from what the repo tracks (a python lockfile, or a node one), renders a
Dockerfile from a small template, writes it into the repo at docker/smortboard-repo.Dockerfile so
a person can review, edit and commit it, and runs `docker build` on the host - the same actor as
every other docker call the board makes. The generated file is never overwritten once it exists,
and neither is an image tag the operator set by hand (set_repo_image does that unconditionally;
this module only ever writes what it itself detected and built).

WHY the gate runs with --network none: nothing can be installed at test time, so everything the
tests need must already be baked into the image (see docker/repo.Dockerfile's own docstring).
"""

from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

_DOCKERFILE_PATH = "docker/smortboard-repo.Dockerfile"
_BUILD_TIMEOUT_SECONDS = 900

# card.Dockerfile's own tag - the repo image builds FROM it, same as the hand-written example
_BASE_CARD_IMAGE = "smortboard-card:latest"

# labels baked into a repo image at build time (see build_repo_image) and read back by
# check_image_freshness - the only contract between "what was built" and "what is true now"
LOCK_HASH_LABEL = "smortboard.lock_hash"
BASE_IMAGE_ID_LABEL = "smortboard.base_image_id"

# the files that decide a stack's dependencies - not just the lockfile: pyproject.toml/
# package.json carry the same pins (the ui_base pin included, for python) even before a lock
# command regenerates the lockfile from them, so a hash of the source alone can go stale between
# an edit and the next `uv lock`/`npm install`
_STAMP_INPUTS: dict[str, tuple[str, ...]] = {
    "python": ("uv.lock", "pyproject.toml"),
    "node": ("package-lock.json", "pnpm-lock.yaml", "package.json"),
}

_PYTHON_TEMPLATE = f"""\
# generated by smortboard's repo_image.py - reviewed, edited and committed like any other file.
# rebuild whenever uv.lock changes (the boards panel's rebuild action does this for you).
FROM {_BASE_CARD_IMAGE}

ENV UV_PROJECT_ENVIRONMENT=/opt/venv \\
    UV_PYTHON_INSTALL_DIR=/opt/python \\
    UV_LINK_MODE=copy

WORKDIR /workspace
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen && rm -rf /workspace/*
"""

_NODE_TEMPLATE = f"""\
# generated by smortboard's repo_image.py - reviewed, edited and committed like any other file.
# rebuild whenever the lockfile changes (the boards panel's rebuild action does this for you).
FROM {_BASE_CARD_IMAGE}

WORKDIR /workspace
COPY package.json package-lock.json* pnpm-lock.yaml* ./
RUN if [ -f pnpm-lock.yaml ]; then corepack enable && pnpm install --frozen-lockfile; \\
    else npm ci; fi && rm -rf /workspace/*
"""

# stack name -> (lockfile candidates, dockerfile template). the first lockfile found wins; a repo
# with neither is unrecognised and gets no image at all - see detect_stack
_STACKS: dict[str, tuple[tuple[str, ...], str]] = {
    "python": (("uv.lock", "pyproject.toml"), _PYTHON_TEMPLATE),
    "node": (("package-lock.json", "pnpm-lock.yaml"), _NODE_TEMPLATE),
}


def detect_stack(repo_path: str | Path) -> str | None:
    """ "python", "node", or None for a stack this module does not know how to build - python is
    checked first since a repo can carry both a uv.lock and a package-lock.json (tooling scripts
    alongside the real project) and the card runtime's own base image is python-first"""
    root = Path(repo_path)
    for stack, (lockfiles, _template) in _STACKS.items():
        if any((root / name).exists() for name in lockfiles):
            return stack
    return None


def dockerfile_for(stack: str) -> str:
    try:
        return _STACKS[stack][1]
    except KeyError:
        raise ValueError(f"no template for stack {stack!r}") from None


def lock_hash(repo_path: str | Path, stack: str) -> str:
    """a short hash of every file that decides this stack's dependencies. changes the moment a
    dependency moves (uv.lock, pyproject.toml, or their node equivalents) - stamped onto a built
    image so a later run can tell whether the image still matches what it is about to judge."""
    root = Path(repo_path)
    digest = hashlib.sha256()
    for name in _STAMP_INPUTS.get(stack, ()):
        path = root / name
        if path.exists():
            digest.update(name.encode())
            digest.update(path.read_bytes())
    return digest.hexdigest()[:16]


def _stamp_detail(stack: str) -> str:
    return (
        "pyproject.toml/uv.lock (which also carries the ui_base pin)"
        if stack == "python"
        else "package.json/package-lock.json (or pnpm-lock.yaml)"
    )


@dataclass
class BuildResult:
    ok: bool
    tag: str | None
    log: str
    stack: str | None = None


@dataclass
class ImageFreshness:
    fresh: bool
    reason: str | None  # None, "missing", "lock", or "base"
    detail: str


def _rebuild_hint(repo: dict[str, Any]) -> str:
    image = repo.get("image") or f"{repo['name']}-repo:latest"
    return f"rebuild it - the boards panel does this, or: docker build -t {image} ."


def _default_inspect_runner(cmd: list[str]) -> subprocess.CompletedProcess:
    """the real docker image inspect - swapped for a fake in every test, same reason every other
    docker call in this file takes an injectable run."""
    try:
        return subprocess.run(cmd, capture_output=True, text=True, timeout=30, check=False)
    except (OSError, subprocess.TimeoutExpired) as exc:
        return subprocess.CompletedProcess(cmd, returncode=-1, stdout="", stderr=str(exc))


def check_image_freshness(
    repo: dict[str, Any],
    run: Callable[[list[str]], subprocess.CompletedProcess] = _default_inspect_runner,
) -> ImageFreshness:
    """compares a repo's built image against what would be built right now: its own dependency
    files, and the base image it was built from - with one `docker image inspect` call naming
    both images, since the repo image's own labels carry the base id it was built against.

    A stale image cannot tell you anything about the commit it is asked to judge - it fails the
    gate for a reason that has nothing to do with the card's work (see this module's docstring),
    so this runs before the gate does, not after a red suite.
    """
    image = repo.get("image")
    if not image:
        return ImageFreshness(True, None, "no repo-specific image is set - nothing to check.")
    path = repo.get("path")
    if not path:
        return ImageFreshness(True, None, "no repo path is set - nothing to check.")

    stack = detect_stack(Path(path))
    if stack is None:
        return ImageFreshness(True, None, "no recognised lockfile - nothing to check.")

    result = run(["docker", "image", "inspect", image, _BASE_CARD_IMAGE])
    raw = (result.stdout or "").strip()
    if not raw:
        # a real `docker image inspect` always answers with at least `[]` - blank stdout means
        # this call did not really reach docker, not that both images are missing, so there is
        # nothing trustworthy to compare and the gate itself is left to say what actually failed
        return ImageFreshness(True, None, "could not inspect the image - skipping the check.")
    try:
        found = json.loads(raw)
    except ValueError:
        return ImageFreshness(True, None, "could not parse `docker image inspect` output.")
    by_ref = {}
    for entry in found if isinstance(found, list) else []:
        for ref in (*entry.get("RepoTags", []), entry.get("Id", "")):
            if ref:
                by_ref[ref] = entry

    repo_entry = by_ref.get(image)
    if repo_entry is None:
        return ImageFreshness(
            False, "missing", f"{image} has never been built. {_rebuild_hint(repo)}"
        )

    labels = (repo_entry.get("Config") or {}).get("Labels") or {}
    stamped_lock = labels.get(LOCK_HASH_LABEL)
    if stamped_lock is None:
        return ImageFreshness(
            False,
            "missing",
            f"{image} predates image stamping, so it cannot be judged fresh. {_rebuild_hint(repo)}",
        )
    if stamped_lock != lock_hash(repo["path"], stack):
        return ImageFreshness(
            False,
            "lock",
            f"{image} was built from a different {_stamp_detail(stack)} than this commit "
            f"carries - a dependency moved. {_rebuild_hint(repo)}",
        )

    base_entry = by_ref.get(_BASE_CARD_IMAGE)
    current_base_id = base_entry.get("Id") if base_entry else None
    stamped_base_id = labels.get(BASE_IMAGE_ID_LABEL)
    if current_base_id and stamped_base_id and current_base_id != stamped_base_id:
        return ImageFreshness(
            False,
            "base",
            f"{image} was built from an older {_BASE_CARD_IMAGE} than exists now - the base "
            f"image moved underneath it. {_rebuild_hint(repo)}",
        )

    return ImageFreshness(True, None, f"{image} matches this commit's dependencies and base.")


def _run(cmd: list[str], cwd: Path, run: Any) -> subprocess.CompletedProcess:
    return run(
        cmd,
        cwd=str(cwd),
        capture_output=True,
        text=True,
        timeout=_BUILD_TIMEOUT_SECONDS,
        check=False,
    )


def _base_image_id(repo_path: Path, run: Any) -> str | None:
    """the base card image's current id (its content hash - there is no registry digest for an
    image that only ever exists locally), or None if it has never been built. `run` is the same
    injectable build_repo_image already takes, so this needs no docker daemon in a test either."""
    try:
        result = _run(
            ["docker", "image", "inspect", _BASE_CARD_IMAGE, "--format", "{{.Id}}"],
            repo_path,
            run,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if result.returncode != 0:
        return None
    return result.stdout.strip() or None


def build_repo_image(repo: dict[str, Any], run: Any = subprocess.run) -> BuildResult:
    """detects the stack, writes docker/smortboard-repo.Dockerfile if the repo has none yet, and
    builds it as `<repo-name>-repo:latest`. `run` is subprocess.run by default - tests pass a
    fake so nothing here ever needs a real docker daemon to prove the wiring is right.

    Never overwrites an existing docker/smortboard-repo.Dockerfile - that file is reviewable and
    editable by a person the moment it exists, and this module treats it as theirs from then on.
    """
    repo_path = Path(repo["path"])
    stack = detect_stack(repo_path)
    if stack is None:
        return BuildResult(
            ok=False,
            tag=None,
            log=(
                "no recognised lockfile (uv.lock/pyproject.toml for python, "
                "package-lock.json/pnpm-lock.yaml for node) - build the image by hand and set "
                "the repo's image field instead."
            ),
        )

    dockerfile_path = repo_path / _DOCKERFILE_PATH
    if not dockerfile_path.exists():
        dockerfile_path.parent.mkdir(parents=True, exist_ok=True)
        dockerfile_path.write_text(dockerfile_for(stack))

    if shutil.which("docker") is None:
        return BuildResult(ok=False, tag=None, log="docker is not on PATH.", stack=stack)

    tag = f"{repo['name']}-repo:latest"
    # stamp what this build was made from, so a later run can tell it apart from a stale image
    # without re-running a single test - see check_image_freshness
    labels = [f"--label={LOCK_HASH_LABEL}={lock_hash(repo_path, stack)}"]
    base_id = _base_image_id(repo_path, run)
    if base_id:
        labels.append(f"--label={BASE_IMAGE_ID_LABEL}={base_id}")
    try:
        result = _run(
            ["docker", "build", "-f", str(dockerfile_path), *labels, "-t", tag, "."],
            repo_path,
            run,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return BuildResult(
            ok=False, tag=None, log=f"docker build did not complete: {exc}", stack=stack
        )

    log = (result.stdout or "") + (result.stderr or "")
    if result.returncode != 0:
        # the tail, not the whole log - a build failure is usually one line deep in a wall of
        # cached-layer noise, and the operator reads this in a panel, not a terminal
        tail = "\n".join(log.strip().splitlines()[-40:])
        return BuildResult(ok=False, tag=None, log=tail, stack=stack)
    return BuildResult(ok=True, tag=tag, log=log, stack=stack)
