"""builds a repo's own test image, so registering a repo is enough to run cards on it.

Detects the stack from what the repo tracks (a python lockfile, or a node one), renders a
Dockerfile from a small template, writes it into the repo at docker/smortboard-repo.Dockerfile so
a person can review, edit and commit it, and runs `docker build` on the host - the same actor as
every other docker call the board makes. The generated file is never overwritten once it exists,
and neither is an image tag the operator set by hand (set_repo_image does that unconditionally;
this module only ever writes what it itself detected and built).

WHY the gate runs with --network none: nothing can be installed at test time, so everything the
tests need must already be baked into the image (see docker/repo.Dockerfile's own docstring).
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

_DOCKERFILE_PATH = "docker/smortboard-repo.Dockerfile"
_BUILD_TIMEOUT_SECONDS = 900

# card.Dockerfile's own tag - the repo image builds FROM it, same as the hand-written example
_BASE_CARD_IMAGE = "smortboard-card:latest"

_PYTHON_TEMPLATE = f"""\
# generated by smortboard's repo_image.py - reviewed, edited and committed like any other file.
# rebuild whenever uv.lock changes (the boards panel's rebuild action does this for you).
FROM {_BASE_CARD_IMAGE}

ENV UV_PROJECT_ENVIRONMENT=/opt/venv \\
    UV_PYTHON_INSTALL_DIR=/opt/python \\
    UV_LINK_MODE=copy

WORKDIR /workspace
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen && rm -rf /workspace/*
"""

_NODE_TEMPLATE = f"""\
# generated by smortboard's repo_image.py - reviewed, edited and committed like any other file.
# rebuild whenever the lockfile changes (the boards panel's rebuild action does this for you).
FROM {_BASE_CARD_IMAGE}

WORKDIR /workspace
COPY package.json package-lock.json* pnpm-lock.yaml* ./
RUN if [ -f pnpm-lock.yaml ]; then corepack enable && pnpm install --frozen-lockfile; \\
    else npm ci; fi && rm -rf /workspace/*
"""

# stack name -> (lockfile candidates, dockerfile template). the first lockfile found wins; a repo
# with neither is unrecognised and gets no image at all - see detect_stack
_STACKS: dict[str, tuple[tuple[str, ...], str]] = {
    "python": (("uv.lock", "pyproject.toml"), _PYTHON_TEMPLATE),
    "node": (("package-lock.json", "pnpm-lock.yaml"), _NODE_TEMPLATE),
}


def detect_stack(repo_path: str | Path) -> str | None:
    """ "python", "node", or None for a stack this module does not know how to build - python is
    checked first since a repo can carry both a uv.lock and a package-lock.json (tooling scripts
    alongside the real project) and the card runtime's own base image is python-first"""
    root = Path(repo_path)
    for stack, (lockfiles, _template) in _STACKS.items():
        if any((root / name).exists() for name in lockfiles):
            return stack
    return None


def dockerfile_for(stack: str) -> str:
    try:
        return _STACKS[stack][1]
    except KeyError:
        raise ValueError(f"no template for stack {stack!r}") from None


@dataclass
class BuildResult:
    ok: bool
    tag: str | None
    log: str
    stack: str | None = None


def _run(cmd: list[str], cwd: Path, run: Any) -> subprocess.CompletedProcess:
    return run(
        cmd,
        cwd=str(cwd),
        capture_output=True,
        text=True,
        timeout=_BUILD_TIMEOUT_SECONDS,
        check=False,
    )


def build_repo_image(repo: dict[str, Any], run: Any = subprocess.run) -> BuildResult:
    """detects the stack, writes docker/smortboard-repo.Dockerfile if the repo has none yet, and
    builds it as `<repo-name>-repo:latest`. `run` is subprocess.run by default - tests pass a
    fake so nothing here ever needs a real docker daemon to prove the wiring is right.

    Never overwrites an existing docker/smortboard-repo.Dockerfile - that file is reviewable and
    editable by a person the moment it exists, and this module treats it as theirs from then on.
    Ownership means a repo whose own tests drive a real browser can add a layer for it - see
    docker/screenshot.Dockerfile for the worked example of installing chromium on top of the same
    card base image.
    """
    repo_path = Path(repo["path"])
    stack = detect_stack(repo_path)
    if stack is None:
        return BuildResult(
            ok=False,
            tag=None,
            log=(
                "no recognised lockfile (uv.lock/pyproject.toml for python, "
                "package-lock.json/pnpm-lock.yaml for node) - build the image by hand and set "
                "the repo's image field instead."
            ),
        )

    dockerfile_path = repo_path / _DOCKERFILE_PATH
    if not dockerfile_path.exists():
        dockerfile_path.parent.mkdir(parents=True, exist_ok=True)
        dockerfile_path.write_text(dockerfile_for(stack))

    if shutil.which("docker") is None:
        return BuildResult(ok=False, tag=None, log="docker is not on PATH.", stack=stack)

    tag = f"{repo['name']}-repo:latest"
    try:
        result = _run(
            ["docker", "build", "-f", str(dockerfile_path), "-t", tag, "."], repo_path, run
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return BuildResult(
            ok=False, tag=None, log=f"docker build did not complete: {exc}", stack=stack
        )

    log = (result.stdout or "") + (result.stderr or "")
    if result.returncode != 0:
        # the tail, not the whole log - a build failure is usually one line deep in a wall of
        # cached-layer noise, and the operator reads this in a panel, not a terminal
        tail = "\n".join(log.strip().splitlines()[-40:])
        return BuildResult(ok=False, tag=None, log=tail, stack=stack)
    return BuildResult(ok=True, tag=tag, log=log, stack=stack)
